import type { SportConfig } from '@/types/sport-config'

export const mmaConfig: SportConfig = {
  slug: 'mma',
  name: 'MMA',
  icon: 'MMA',
  accentColor: '#B22222',
  competitions: [
    { slug: 'ufc-flyweight', name: 'Flyweight', competitionType: 'league', seasonLabelFormat: 'year' },
    { slug: 'ufc-bantamweight', name: 'Bantamweight', competitionType: 'league', seasonLabelFormat: 'year' },
    { slug: 'ufc-featherweight', name: 'Featherweight', competitionType: 'league', seasonLabelFormat: 'year' },
    { slug: 'ufc-lightweight', name: 'Lightweight', competitionType: 'league', seasonLabelFormat: 'year' },
    { slug: 'ufc-welterweight', name: 'Welterweight', competitionType: 'league', seasonLabelFormat: 'year' },
    { slug: 'ufc-middleweight', name: 'Middleweight', competitionType: 'league', seasonLabelFormat: 'year' },
    { slug: 'ufc-light-heavyweight', name: 'Light Heavyweight', competitionType: 'league', seasonLabelFormat: 'year' },
    { slug: 'ufc-heavyweight', name: 'Heavyweight', competitionType: 'league', seasonLabelFormat: 'year' },
    { slug: 'ufc-womens-strawweight', name: "Women's Strawweight", competitionType: 'league', seasonLabelFormat: 'year' },
    { slug: 'ufc-womens-flyweight', name: "Women's Flyweight", competitionType: 'league', seasonLabelFormat: 'year' },
    { slug: 'ufc-womens-bantamweight', name: "Women's Bantamweight", competitionType: 'league', seasonLabelFormat: 'year' },
    { slug: 'ufc-womens-featherweight', name: "Women's Featherweight", competitionType: 'league', seasonLabelFormat: 'year' },
    { slug: 'ufc-catch-weight', name: 'Catch Weight', competitionType: 'league', seasonLabelFormat: 'year' },
  ],
  leaderboardColumns: [
    { key: 'player', label: 'Fighter', sortable: false },
    { key: 'fights', label: 'Fights', sortable: true, tooltip: 'Fights: Total fights' },
    { key: 'wins', label: 'Wins', sortable: true, tooltip: 'Wins: Total fights won' },
    { key: 'losses', label: 'Losses', sortable: true, tooltip: 'Losses: Total fights lost' },
    { key: 'win_pct', label: 'Win%', sortable: true, tooltip: 'Win Percentage: Percentage of fights won' },
    { key: 'sig_strikes_per_min', label: 'SLpM', sortable: true, tooltip: 'Significant Strikes Landed per Minute: Average significant strikes landed per minute' },
    { key: 'sig_strike_acc', label: 'StrAcc%', sortable: true, tooltip: 'Significant Striking Accuracy: Percentage of significant strikes that land' },
    { key: 'takedown_avg', label: 'TDAvg', sortable: true, tooltip: 'Takedown Average: Average takedowns landed per 15 minutes' },
    { key: 'sub_avg', label: 'SubAvg', sortable: true, tooltip: 'Submission Average: Average submissions attempted per 15 minutes' },
  ],
  defaultSortKey: 'wins',
  expandedChartConfig: {
    type: 'radar',
    primaryDataKey: 'wins',
    label: 'Fight Profile',
    excludeKeys: ['Fights', 'Wins', 'Losses'],
  },
  rankingLabel: 'Fighter',
  hasTeams: false,
  hasPositionFilter: false,
}
